import { ArrowDown, ArrowRight, ShieldCheck, Sparkles, Truck, RotateCcw } from 'lucide-react'; import { Link } from 'react-router-dom'; import ProductCard from '../components/ProductCard'; import { categories, products } from '../data/products';
export default function Home({addToCart}){return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">CURADORIA 2026 · DROP 01</span><h1>NÃO VENDEMOS<br/>TÊNIS.<br/><em>CRIAMOS PRESENÇA.</em></h1><p>Os sneakers mais desejados do momento, selecionados para quem transforma cada passo em identidade.</p><div className="hero-actions"><Link className="btn primary" to="/catalogo">Explorar coleção <ArrowRight/></Link><a className="btn ghost" href="#destaques">Ver destaques</a></div><div className="hero-proof"><div><strong>4,9/5</strong><span>avaliação média</span></div><div><strong>+12 mil</strong><span>clientes ZAPA</span></div></div></div><div className="hero-visual"><div className="hero-stamp">ZAPA<br/>SELECTED</div><img src="https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1600&q=95" alt="Sneaker premium"/><span className="floating-tag">DROP 01<br/><b>LIMITED</b></span></div><a className="scroll-cue" href="#destaques"><ArrowDown/> Descubra</a></section>
 <section className="trust"><div><Truck/><span><strong>Frete grátis</strong> acima de R$ 499</span></div><div><RotateCcw/><span><strong>Troca fácil</strong> em até 30 dias</span></div><div><ShieldCheck/><span><strong>Compra segura</strong> e autenticidade</span></div><div><Sparkles/><span><strong>Curadoria ZAPA</strong> peças selecionadas</span></div></section>
 <section className="section" id="destaques"><div className="section-head"><div><span>DESTAQUES</span><h2>Escolhas que falam por você.</h2></div><Link to="/catalogo">Ver todos <ArrowRight/></Link></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p} addToCart={addToCart}/>)}</div></section>
 <section className="manifesto"><div><span>MANIFESTO ZAPA</span><h2>O básico não deixa memória.</h2><p>Acreditamos em peças que atravessam tendências e traduzem personalidade. Cada modelo da nossa curadoria existe por um motivo.</p><Link className="btn light" to="/catalogo">Conheça a seleção <ArrowRight/></Link></div><img src="https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1400&q=90" alt="Coleção ZAPA"/></section>
 <section className="section" id="colecoes"><div className="section-head"><div><span>COLEÇÕES</span><h2>Encontre o seu movimento.</h2></div></div><div className="category-grid">{categories.map(c=><Link to="/catalogo" className="category" key={c.name}><img src={c.image} alt={c.name}/><div><span>EXPLORAR</span><h3>{c.name}</h3><ArrowRight/></div></Link>)}</div></section>
 <section className="quote"><span>THE ZAPA EFFECT</span><blockquote>“Você não precisa dizer nada quando o seu estilo já chegou primeiro.”</blockquote></section>
 </>}
